### ISSUE TITLE
Ideas and suggestions and some crazy suggestions for research purpose.

### ISSUE THREAD

**Issue by KevinKhachariya** [magnifiques/the-meal-app#1]
@magnifiques I am the testuser@gmail.com in your database.

### Ideas

- Have you considered using A.I. tools like ChatGPT to help you populate the random meals data?

### Suggestions

- It is better to remove the token expiration logic from frontend and let backend handle it.
- I would suggest trying and exploring HTTP Only cookies if you never did for tokens management.
- Also a great opportunity to try out Algolia for indexing.

### Crazy suggestions ( to try something if you want to add more complexity to this project )

- Let AI review user's recipies and troll as Gordon Ramsey level feedback.
- Let AI generate and suggest you recipes based on user's mood / taste input. Like "damn I need to eat something sweet but not so sweet and takes like 5 minutes to make because I am lazy"
- See the pattern here, adding A.I. unlocks things which would otherwise take too long to make without A.I.

**Comment by KevinKhachariya** [comment]
Another crazy part here is that I would just ask A.I. to produce the code for the crazy stuff I wrote above. 🤯
![SmartThinkingGIF](https://user-images.githubusercontent.com/84901910/230704887-6193377a-5abf-42d5-8ba5-61af17438c65.gif)

**Comment by magnifiques** [comment]
I made this app just for educational purposes.

**Comment by magnifiques** [comment]
Thank you for the suggestions and ideas though

**Comment by KevinKhachariya** [comment]
> I made this app just for educational purposes.

If this is for educational purpose. Go for Algolia and ChatGPT integration and throw in some 3rd part AuthO integrations while at it if you have some time and interested to learn them.
